organization=[
         #"paresh",
         #"roshni",
         #"TFE-DEV",
         "TFE-PROD-NEW"
         ]
github_repo=[
       #"TFE-NONPROD",
       #"TFE-DEV",
       #"TFE-PROD-NEW",
       #"TFE-PROD-NEW1",
       "TFE-PROD-NEW2"
       ]
workspace=[
    #"TFE-PROD-APP1",
    #"TFE-PROD-APP2",
    #"TFE-PROD-APP3",
    "TFE-PROD-APP4"
    ]
githubuser="avisek12"

